---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template
  namespace: template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template
  template:
    metadata:
      labels:
        app: template
    spec:
      restartPolicy: Always
      containers:
        - name: service
          image: template:v1
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5000
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
